import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log('banner Button')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick}/>
        </h1>
      </main>   
    </div>
  )
}
